### ISSUE TITLE
the wps.desktop can't be found in /usr/share/applications/default.list

### ISSUE THREAD

**Issue by FUjr** [cyrpaut/wps-2019-snap#1]
the wps.desktop can't be found in /usr/share/applications/default.list  as the origenal verison.so that i can't change the default startup with "nano /usr/share/applications/default.list".It's inconvenient to change so much startup.
And i am a newbie in both english and computer....
sorry for my poor English

**Comment by cyrpaut** [comment]
Hello,
I don't have such problem. Which distibution are you using?
